global DISCORD_POSTED_URL, DISCORD_VERIFY_URL, SECRET_KEY, ADMIN_PSWD, HASH_SALT, DBG_MODE, MYSQL_URL, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE   

SECRET_KEY = None
ADMIN_PSWD = None
HASH_SALT = None
DBG_MODE = None
DISCORD_POSTED_URL = None
DISCORD_VERIFY_URL = None
MYSQL_URL = None
MYSQL_PORT = None
MYSQL_USER = None
MYSQL_PASSWORD = None
MYSQL_DATABASE = None