global DISCORD_POSTED_URL, DISCORD_VERIFY_URL, DB_PATH, SECRET_KEY, ADMIN_PSWD, HASH_SALT, DBG_MODE

DISCORD_POSTED_URL = None
DISCORD_VERIFY_URL = None
DB_PATH = None
SECRET_KEY = None
ADMIN_PSWD = None
HASH_SALT = None
DBG_MODE = None